### ISSUE TITLE
Need Better Solution for EXTn xattr Attribs

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/ash-linux-formula#120]
The fix for formula-issue #118 is a kludge. Need to look at writing an actual file.\* module for SaltStack as it does not currently look like such is on the SaltStack roadmap (no target release set in notation for saltstack/salt#27094)

**Comment by ferricoxide** [comment]
This bug is over a year old and the referenced issue in SaltStack is still open. Further, EL6 is coming up on its final scheduled release prior to End of Sales Life. Will keep issue open for tracking, but this will likely end up a WONTFIX.

**Comment by lorengordon** [comment]
@KevinPlus3 is looking into this now.

**Comment by KevinPlus3** [comment]
file.managed now uses file.chattr and file.lsattr to allow one to handle attributes of files/directories on Linux system.  The branch has been merged into https://github.com/saltstack/salt.git on the develop branch.

**Comment by ferricoxide** [comment]
OBE: EL6 no longer supported by vendor
