### ISSUE TITLE
Extra `sha512` token in `/etc/pam.d/sytem-auth-ac`

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-linux-formula#134]
The initial application of ash-linux results in an extra `sha512` token in `/etc/pam.d/system-auth-ac`. E.g.:

```
password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok sha512
```

The state cat2/V38574 is the only state that modifies this token. Investigation reveals that grep does not seem to use the `\s` token to match any whitespace character (including new line) and also does not like `[\s]` in any circumstance I can determine.

**Comment by ferricoxide** [comment]
Is this one able to be closed?

**Comment by lorengordon** [comment]
I think I was waiting on you to review/test the corresponding PR; the issue should close automatically once the PR is merged...

**Comment by ferricoxide** [comment]
Ok. Cool. I missed the handshake.
