### ISSUE TITLE
Reorganize File-Hierarchy to better support use with EL6 *and* EL7

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/ash-linux-formula#138]

**Comment by ferricoxide** [comment]
@lorengordon 

Getting ready to do a PR for this. I've run it on both an EL6 and an EL7 host. And it runs to normal completion on both.

**Comment by lorengordon** [comment]
I think it is sufficient for now if the desired, version-specific states apply successfully via `salt-call --local ash-linux.stig` on both el6 and el7...

**Comment by ferricoxide** [comment]
I'd been doing `salt-call --local ash-linux` on both. It actually helped me uncover a casting-error in one of the SCAP-handlers (fixed).
