### ISSUE TITLE
Issues when updating to 6.8+ from versions < 6.8

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/ash-linux-formula#147]
Need to update documentation:

- Small-memory configurations — `t1.micro` or smaller — experience yum-breakage that is only fixable by temp-upgrading to an instance-type equivalent to  `t2.micro` or larger.
- ~~When `cat3/V38687` is run via Highstate and the EL6 version is < 6.8, the `cat3.V38687` state will assert a false failure notification. The false-failure is avoided if starting-AMI is EL 6.8 or higher.~~

**Superficially Related:**
- Small memory configurations — `t1.micro` or smaller — will fault in the `SCC` formula due to memory-starvation.

**Comment by lorengordon** [comment]
Crossed out the second bullet, as https://github.com/plus3it/ash-linux-formula/pull/148 makes it OBE.

**Comment by lorengordon** [comment]
This is more of a note now than an issue we can fix, so I'm going to close it. We can re-open it if we find other problems that we can address.
