### ISSUE TITLE
Find alternative to `pkg.check_db`

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-linux-formula#155]
`pkg.check_db` is no longer available in salt 2016.3. Need to find an alternative approach.

The function is only used here, https://github.com/plus3it/ash-linux-formula/blob/a84e2bdbf1f2928c166d4067dcae539d6926d9d9/ash-linux/el6/STIGbyID/cat1/V38666.sls

**Comment by ferricoxide** [comment]
Change to `pkg.latest_version` _should_ fix ...but can't test against a scenario where the test evaluates to `true` :p 

    diff --git a/ash-linux/el6/STIGbyID/cat1/V38666.sls b/ash-linux/el6/STIGbyID/cat1/V38666.sls
    index 36a5e40..5f4aba8 100644
    --- a/ash-linux/el6/STIGbyID/cat1/V38666.sls
    +++ b/ash-linux/el6/STIGbyID/cat1/V38666.sls
    @@ -46,7 +46,7 @@ cmd_V{{ stig_id }}-cleanChck:
    
     {%- else %}
    
    -    {%- if salt['pkg.check_db'](MSFEpkg)[MSFEpkg]['found'] %}
    +    {%- if salt['pkg.latest_version'](MSFEpkg) %}
    
     # If not installed, see if it's available in the Yum repos
     pkg_V{{ stig_id }}:
