### ISSUE TITLE
Some sls is using `cmd.run` in Jinja without `python_shell`

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-linux-formula#193]
This alias mentioned in the deprecation warning is getting removed in the next version of salt, so we need to find these and fix them up.

Unfortunately, the error does not indicate _which_ sls contains the deprecated usage.

```
/usr/lib/python2.6/site-packages/salt/utils/templates.py:73: DeprecationWarning: Starting in 
2015.5, cmd.run uses python_shell=False by default, which doesn't support shellisms (pipes, 
env variables, etc). cmd.run is currently aliased to cmd.shell to prevent breakage. Please 
switch to cmd.shell or set python_shell=True to avoid breakage in the future, when this 
aliasing is removed.
```

**Comment by ferricoxide** [comment]
This is closed by one of this morning's PRs, correct?

**Comment by lorengordon** [comment]
It will be closed automatically when the cross-referenced PR is merged, since I got the issue reference correct in the commit.
