### ISSUE TITLE
Find another way to iterate over local users

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-linux-formula#223]
Once joined to a domain, `salt['user.list_users']()` will iterate over _every_ domain user... Works when calling salt directly, but deadlocks when running it via subprocess and capturing the output (as done in watchmaker--also looking for a solution to the deadlock there...).

https://github.com/plus3it/ash-linux-formula/blob/master/ash-linux/el6/STIGbyID/cat1/V38491.sls#L32

**Comment by ferricoxide** [comment]
This is a side-effect of how Salt interrogates user objects. Basically, it's doing/emulating a generic `getent passwd`. If this were Solaris, you could limit the scope of the `getent` call. Linux doesn't support that kind of scoping. You'd need to do something uglier like `cut -d: -f 1 /etc/passwd` to create a list of local-only users, then iterate _that_ list.

**Comment by lorengordon** [comment]
Seems to be a side-effect of the underlying python module. Here is the method salt uses to grab all the users:

* https://docs.python.org/2/library/pwd.html#pwd.getpwall

Doesn't seems to have any options to restrict or scope the result-set.

**Comment by ferricoxide** [comment]
Yeah. Solaris is about the only OS I know of that had an option for restricting things (in higher-level commands like `getent` - probably because they assumed that most sites were using multiple auth-sources). My assumption would be that Python's simply borrowing/emulating the generic [getpwent()](http://man7.org/linux/man-pages/man3/getpwent.3.html) C routines.

**Comment by lorengordon** [comment]
Yes, that's exactly what it is doing :(

https://github.com/python-git/python/blob/715a6e5035bb21ac49382772076ec4c630d6e960/Modules/pwdmodule.c#L139-L170

**Comment by lorengordon** [comment]
Oi. We got a lot of `list_user` usage:

* https://github.com/plus3it/ash-linux-formula/search?q=list_users&type=Code&utf8=%E2%9C%93

**Comment by ferricoxide** [comment]
Fortunately, pretty much the entirety of the el7/STIGbyID tree can be dumped.

**Comment by lorengordon** [comment]
Resolved:
* https://github.com/plus3it/ash-linux-formula/pull/224
* https://github.com/plus3it/ash-linux-formula/pull/226
