### ISSUE TITLE
FIPS-handler needs to account for stand-alone /boot partition

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/ash-linux-formula#235]
Current FIPS-mode selector appears to only account for the `fips=<0|1>` element of GRUB2's kernel options line. This is sufficient if the starting-point system either has a combined `/` and `/boot` (as is normal for generic Linux Amazon Machine Imaes) or on split `/` and `/boot` systems where the requisite `boot=` token is already present (as is normal for AMIs created via the [spel](/plus3it/spel)/[amigen](/ferricoxide/AMIgen7) process). However, the current handler will be insufficient for split `/` and `/boot` systems where the requisite `boot=` token is _not_ already present (e.g., a CD-built EL7 host deployed via VMware/VirtualBox/etc.)

In the last scenario, when FIPS is enabled, the modified system will halt on reboot due to FIPS not "trusting" the `/boot` partition's contents. Need to update FIPS-handler to ensure appropriate `boot=` token is present.

**Comment by ferricoxide** [comment]
So, is this fixed, now, in one of the PRs (i.e., should the PR have included a `closes` tag)?

**Comment by KevinPlus3** [comment]
Yes!
