### ISSUE TITLE
The V38511 module superseded by aws-vpc-nat package

### ISSUE THREAD

**Issue by chriswvu** [plus3it/ash-linux-formula#237]
The aws-vpc-nat rpm is setting  net.ipv4.ip_forward = 1 via a script in the /etc/sysctl.d/10-nat-settings.conf                                  file causing a CAT II finding.

**Comment by ferricoxide** [comment]
Per out-of-band conversation (mail thread), this appears to be an ordering issue. V38511 module currently implements setting directly in `/etc/sysctl.conf` file, however, presence of the named RPM exposes an order-processing issue.

Red Hat solution-document [#27660](https://access.redhat.com/solutions/27660) provides a hint that the STIG's fix-method was likely authored during the pre-6.2 release-era when EL6 didn't pick up directives from files hosted `/etc/sysctl.d`. Will need to update the STIG-handler to reflect the post-6.2 reality and move the setting of the `net.ipv4.ip_forward` value to an `/etc/sysctl.d` file that gets processed later than the one shipped in the `aws-vpc-nat` RPM (presumably something like `/etc/sysctl.d/99-net-ip_forward.conf`.

**Comment by ferricoxide** [comment]
Awesome... Looks like it's not good enough for Amazon to simply set up a freaking file in `/etc/sysctl.d`. No. That would be too damned easy. In addition to freaking polluting the settings-directory, they also include a "helpful" script, `/usr/sbin/configure-pat.sh` that's invoked via `/etc/init/nat.conf`. A real "belt-and-suspenders" kind of solution. Seriously: I've seen sledgehammers designed to drive rail-spikes that were less overkill than this method.

In sum, "doing things the Right Way(TM) and moving the `sysctl` functionality for ip-forwarding to `/etc/sysctl.d` is not sufficient. Will need to also ensure that the offending RPM is not present.

**Comment by ferricoxide** [comment]
Closed by #238
