### ISSUE TITLE
Can't Rely on SCAP Content to Force a `yum update` 

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/ash-linux-formula#248]
### Problem Description:

Relying on the SCAP bundles to force patch-updates does not reliably result in an up-to-date system

### Expected Behavior:

`yum list updates` returns null when it is run after ASH has hardened system 

### Actual Behavior:

`yum list updates` may not return null when it is run after ASH has hardened system. Output depends on whether the SCAP profile included an update rule

### (Detailed) Steps to reproduce:

Due to variability of SCAP content, can only describe "failing" case:

1. Deploy system
1. Run ash-linux-fomula (e.g., via [watchmaker](/plus3it/watchmaker) 
1. Execute `yum list updates`

If return from last is non-null, the SCAP content didn't enforce an RPM-update procedure.

### (Optional) Fix recommendation:

Add a module similar to the EL6 module that calls `yum update`

**Comment by lorengordon** [comment]
Fixed by #250
