### ISSUE TITLE
Add formula to ensure "LogLevel" is set to "VERBOSE" in sshd_config

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/ash-linux-formula#253]
Standard `LogLevel` is `INFO`. This log-level does not capture connecting users's SSH keys. Probably want to change this &mdash; at least on hosts that are not AD-integrated.

**Comment by ferricoxide** [comment]
See Watchmaker [Issue 704-A](https://github.com/plus3it/watchmaker/issues/704#issuecomment-432350839)

**Comment by ferricoxide** [comment]
@ewierschke you said this one came from one of the `oscap` profiles? You happen to have a record of the rule or vulnerability ID associated with it? I need to put the handler for this _somewhere_ and, right now, only really have the `VendorSTIG`, `STIGbyID` and `SCAPonly` rule-trees.

**Comment by ewierschke** [comment]
The scan profile used was the C2S profile... the Rule ID referenced sshd_set_loglevel_info but then the identifiers and references just had the number 5.2.3 and a link to the v1.1.0 CIS benchmark.  Looking at the v2.2.0 CIS benchmark it does still appear to be in there as a rule, and in section 5.2.3 of their document.  Doesn't appear to be in the STIG from what I can find.

**Comment by ferricoxide** [comment]
Bugger... Guess I need to add a new tree for `CIS`-specific stuff. 💩
