### ISSUE TITLE
[Feature Request] Add script-linting check to CI workflows

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/ash-linux-formula#409]
**Is your feature request related to a problem? Please describe.**

Currently, this project's CI does not include any kind of linting for the various helper-scripts used throughout the project. This gap needs to be addressed

**Describe the solution you'd like**

Update the CI definitions to include, at the very least, syntax- and style-checking of the various helper-scripts with the [`shellcheck`](https://github.com/koalaman/shellcheck) tool.

**Describe alternatives you've considered**

**Additional context**

Depends on prior merge of fixes for #410

**Comment by lorengordon** [comment]
Our (new) standard way of doing this would be to use tardigrade-ci and the reusable workflow from the [actions-workflows](https://github.com/plus3it/actions-workflows/) project.

We can do that by adding this same workflow file, [.github/workflows/lint.yml](https://github.com/plus3it/repo-template/blob/main/.github/workflows/lint.yml). And also completing the [Makefile Include](https://github.com/plus3it/tardigrade-ci#makefile-include) setup for tardigrade-ci.

**Comment by ferricoxide** [comment]
Which is why I'm linting them, now. Not so much that I'm wanting to refactor the old scripts, but, when we were _adding_ the EL8s, some errors leaked through because of lack of linting. Plus, I'd like to have it in place before we start tackling the (eventual) EL9 content.

**Comment by ferricoxide** [comment]
Ok., that went more-quickly than expected. Were fewer changes required than I was anticipating.
