### ISSUE TITLE
RHEL 8 Scap Scan finding V-230229

### ISSUE THREAD

**Issue by justinmackey** [plus3it/ash-linux-formula#454]
### Problem Description:

No valid DoD root CA installed when running following command:

$ sudo openssl x509 -text -in /etc/sssd/pki/sssd_auth_ca_db.pem

### Expected Behavior:

Root ca file returns DoD-issued certificate with a valid date and installed in the /etc/sssd/pki/sssd_auth_ca_db.pem location

### Actual Behavior:

Command returns the file /etc/sssd/pki/sssd_auth_ca_db.pem does not exist

### (Detailed) Steps to reproduce:

Run $ sudo openssl x509 -text -in /etc/sssd/pki/sssd_auth_ca_db.pem

### (Optional) Fix recommendation:

Either submit a PR or describe, in as great of detail possible, how to fix the problem.

**Comment by ferricoxide** [comment]
You're executing a bad test. The correct way to verify root CAs is with the `trust list`. For example, to enumerate all installed DoD root CAs, issue:

```bash
# trust list --filter=ca-anchors | grep -i DoD
```

This will return a list similar to:

```text
[…elided…]
    label: DoD WCF Root CA 1
    label: DoD Root CA 6
    label: DoD Root CA 5
    label: DoD Root CA 4
    label: DoD Root CA 3
[…elided…]
```
