### ISSUE TITLE
CCE-27164-3 will produce bogus traceback if IPv6 is disabled

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/ash-linux-formula#54]
Security tools want `net.ipv6.conf.default.accept_ra` tunable set in `/etc/sysctl.conf` even though IPv6 is already disabled. Forcing this behavior via `sysctl.present` Salt module will result in the dumping of a semi-spurious traceback: the `sysctl.present` will add the entry to `/etc/sysctl.conf`, but because its attempt to set the in-memory value receives an error back from the OS, it dumps a traceback that is should probably suppress.

[reported as SaltStack Issue #21300](https://github.com/saltstack/salt/issues/21300)

**Comment by lorengordon** [comment]
This fix was merged into v2014.7.4...

**Comment by lorengordon** [comment]
This one good to close? We're using at least 2015.5.5 now, or 2015.8.1...

**Comment by ferricoxide** [comment]
Nope. When I was testing the updates to the password modules, I was lazy and did a full formula-rerun. Each time, there were seven errors around the IPv6 components - this was one of them.

:disappointed:

**Comment by ferricoxide** [comment]
OBE: EL6 no longer supported by vendor
